name: Rebase Open PRs on Merge

on:
  pull_request:
    types:
      - opened
      

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "vishnu4reddy"
          git config user.email "vishnu4reddy"

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh
      
      - name: Get list of open PRs
        id: pr_list
        run: |
          prs=$(gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"')
          echo "prs=$prs" >> $GITHUB_ENV

      - name: Rebase each open PR
        run: |
          for pr in $prs
          do
            pr_number=$(echo $pr | awk '{print $1}')
            pr_branch=$(echo $pr | awk '{print $2}')
            
            echo "Rebasing PR #$pr_number ($pr_branch)"

            git fetch origin main
            git checkout $pr_branch

            echo "Before rebase:"
            git log --oneline --decorate --graph

            git rebase origin/main

            if [[ $? -ne 0 ]]; then
              echo "Rebase failed for PR #$pr_number due to conflicts. Please resolve manually."
              exit 1
            else
              echo "Rebase successful for PR #$pr_number"
            fi

            echo "After rebase:"
            git log --oneline --decorate --graph

            git push origin $pr_branch --force-with-lease
          done
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



