name: Rebase Open PRs on Merge
on:
  push:
    branches:
      - main 
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "vishnu4reddy"  # Replace with your GitHub username 
          git config user.email "vishnu4reddy@users.noreply.github.com"  # Ensure this email is valid 

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Get list of open PRs
        id: pr_list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure your token has proper permissions
        run: |
          prs=$(gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"')
          echo "Open PRs: '$prs'"  # Quoting output for better visibility
          
          # Check if no PRs were returned
          if [[ -z "$prs" ]]; then
            echo "No open PRs found."
            exit 0
          fi
          # Setting each PR in GITHUB_ENV directly
          IFS=$'\n'  # Set IFS to newline for reading
          for pr in $prs; do
            pr=$(echo "${pr}" | xargs)  # Trim whitespace
            echo "Setting pr_value: '$pr'"  # Debug output
            echo "pr_value=$pr" >> $GITHUB_ENV  # Use this format
          done

      - name: Debug PR List Output
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is provided here as well
        run: |
          echo "Debugging PR List Output:"
          # This will print all pr_value entries set
          gh pr list --state open
          if [ $? -ne 0 ]; then
              echo "Error: Failed to list PRs"
              exit 1
          fi

      - name: Rebase each open PR
        run: |
          set -x
          git fetch origin  # Get all branches
          # Loop through each pr_value set in the environment
          while IFS= read -r pr; do
            echo "Processing PR: '$pr'"
            pr_number=$(echo "$pr" | awk '{print $1}')   # Extract the first column as the number
            pr_branch=$(echo "$pr" | awk '{print $2}')   # Extract the second column as the branch
            echo "Extracted PR number: $pr_number and branch: $pr_branch"
            
            # Check if the branch name is empty
            if [[ -z "$pr_branch" ]]; then
              echo "Error: Branch name for PR #$pr_number is empty."
              continue
            fi
            
            # Checkout the branch
            git checkout origin/"$pr_branch" || { echo "Failed to checkout $pr_branch"; exit 1; }
            echo "Checked out branch $pr_branch"
            
            # Attempt to rebase the branch
            if git rebase origin/main; then
              echo "Rebase successful for $pr_branch"
              
              # Push the rebased branch
              git push origin "$pr_branch" --force-with-lease || { echo "Failed to push $pr_branch"; exit 1; }
              echo "Successfully pushed changes for $pr_branch"
            else
              echo "Rebase failed for $pr_branch due to conflicts. Skipping this PR."
              git rebase --abort  # Abort the rebase process to avoid issues
              continue  # Skip to the next PR
            fi
          done <<< "$(printenv | grep pr_value | cut -d'=' -f2)"  # Read from the environment

            
