name: Rebase Open PRs on Merge

on:
  push:
    branches:
      - main  

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "vishnu4reddy" 
          git config user.email "vishnu4reddy" 

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Get list of open PRs
        id: pr_list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the token explicitly
        run: |
          prs=$(gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"')
          echo "Open PRs: $prs"  # Debugging step to print out the list of PRs
          echo "prs=$prs" >> $GITHUB_ENV

      - name: Rebase each open PR
        run: |
          echo "The following PRs were found: ${{ env.prs }}"  # Debugging to check what was passed
          for pr in $(echo "${{ steps.pr_list.outputs.prs }}" | tr " " "\n")
          do
            pr_number=$(echo $pr | awk '{print $1}')
            pr_branch=$(echo $pr | awk '{print $2}')
            
            echo "Rebasing PR #$pr_number ($pr_branch)"

            git fetch origin main
            git checkout $pr_branch
            git rebase origin/main
            git push origin $pr_branch --force-with-lease
          done
