name: Rebase Open PRs on Merge

on:
  push:
    branches:
      - master  

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "vishnu4reddy"
          git config user.email "vishnu4reddy"

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh
        
      - name: Get list of open PRs
        id: pr_list
        run: |
          prs=$(gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"')
          echo "prs=$prs" >> $GITHUB_ENV

      - name: Rebase each open PR
        run: |
          for pr in $prs
          do
            pr_number=$(echo $pr | awk '{print $1}')
            pr_branch=$(echo $pr | awk '{print $2}')
            
            echo "Rebasing PR #$pr_number ($pr_branch)"

            # Fetch the base branch (master)
            git fetch origin master

            # Checkout the PR branch and rebase onto the base branch
            git checkout $pr_branch
            git rebase origin/master

            # Push the rebased branch (force-push safely)
            git push origin $pr_branch --force-with-lease
          done
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
